// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-cGSLufsmaCKEtxjEhVeFk3KTfFiOvz4',
    appId: '1:395186008655:web:3f3c412dfc8f1bd97b703a',
    messagingSenderId: '395186008655',
    projectId: 'food-finder-b129b',
    authDomain: 'food-finder-b129b.firebaseapp.com',
    storageBucket: 'food-finder-b129b.appspot.com',
    measurementId: 'G-RR7GTNV7GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK8ecunSXuHaLaPuhzQN_oqCRkfU95uf8',
    appId: '1:395186008655:android:69d7bbfa85bf5b437b703a',
    messagingSenderId: '395186008655',
    projectId: 'food-finder-b129b',
    storageBucket: 'food-finder-b129b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDWVcwrawazzeq-yZDk1pd_HgnCuy4mlY',
    appId: '1:395186008655:ios:ba41550703b62c047b703a',
    messagingSenderId: '395186008655',
    projectId: 'food-finder-b129b',
    storageBucket: 'food-finder-b129b.appspot.com',
    iosBundleId: 'com.example.locommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDWVcwrawazzeq-yZDk1pd_HgnCuy4mlY',
    appId: '1:395186008655:ios:254c166f0ced8b437b703a',
    messagingSenderId: '395186008655',
    projectId: 'food-finder-b129b',
    storageBucket: 'food-finder-b129b.appspot.com',
    iosBundleId: 'com.example.locommerce.RunnerTests',
  );
}
